# Generated by Django 5.2.17 on 2026-09-01 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0002_choretemplate_choreinstance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choreinstance',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='chores.choretemplate'),
        ),
    ]
